// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TodoLib.Models;

public partial class ItemContext : DbContext
{

    public ItemContext()
    {
        
    }

    public ItemContext(DbContextOptions<ItemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ToDo> ToDos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ToDo>(entity =>
        {
            entity.HasKey(e => e.TodoId).HasName("PK__ToDo__9586255225EC0C24");
            entity.Property(t => t.Priority).HasConversion<int>();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(Secret.ConnectionString);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}