// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace TodoLib.Models;

[Table("ToDo")]
public partial class ToDo
{
    [Key]
    public int TodoId { get; set; }

    [Required]
    [StringLength(25)]
    public string Title { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    public PriorityLevel Priority { get; set; }

    public bool IsCompleted { get; set; }


    public ToDo()
    {
        
    }

    public ToDo(int todoId, string title, string description, PriorityLevel priority, bool isCompleted)
    {
        TodoId = todoId;
        Title = title;
        Description = description;
        Priority = priority;
        IsCompleted = isCompleted;
    }

}